# Generated by Django 4.2.13 on 2026-05-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(db_index=True, max_length=500, unique=True),
        ),
    ]
